title: MCPeer
description: Visual platform for creating, configuring, and managing Model Context Protocol (MCP) servers
baseurl: ""
url: "https://marcellopato.github.io/mcpeer"

# GitHub Pages configuration
plugins:
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - docker/
  - vendor/
  - node_modules/

# Logo and favicon
logo: /images/logo-large.svg
favicon: /images/favicon.svg
